---
title: Welcome to ML!
subtitle: Lecture 0
title-slide-attributes:
  data-slide-number: none
format: revealjs
auto-stretch: false
---

# Course Details

:::

## Daily Structure

-   A Days:
    -   two morning lectures
    -   afternoon homework and project check
-   B Days:
    -   one morning lecture
    -   one morning Lab
    -   afternoon standard quiz

## Themes: what, why, and how {.smaller}

-   **What:** the plot
    -   blah

. . .

-   **How:** the process
    -   blah

. . .

-   **Why:** the theory
    -   Tie together "how" and "what" 

# But first...

## Show and tell {.smaller}

::: task
-   Form a small group (2-4 people) with people sitting around you

-   First, introduce yourselves to each other -- name (and proper pronunciation of name), year, major, where are you from, etc.

:::

# Course components

## Course website

::: {.large style="text-align: center;"}
[vizdata.org](https://chefs-kiss.github.io/ML_J2026/)
:::

::: {.hand style="text-align: center;"}
aka "the one link to rule them all"
:::

::: {style="text-align: center;"}
```{=html}
<iframe width="1000" height="400" src="https://chefs-kiss.github.io/ML_J2026/" frameborder="1" style="background:white;"></iframe>
```
:::

## Lectures {.smaller}

-   In person

-   Attendance is required

-   A little bit of everything:

    -   Traditional lecture
    -   Live coding + demos
    -   Short exercises 
    -   Discussions

## Labs

-   Occurs every other day in the morning (check schedule for 💻)

## Quizzes

-   Occurs every other day in the afternoon (check schedule for 📄) 

## Announcements

-   Sent via email



# Wrap up


## This week's tasks

1.  Create a GitHub account if you don't have one

2.  Read the syllabus

4.  Post on Discussion board

5.  Complete the readings