# CLS readings

## ISLP selected readings
Dive deeper in the content we'll be covering. These articles can be quite math-heavy. If anything is unclear, don’t hesitate to reach out to your instructor. Aim to grasp the big-picture ideas so you can explain each topic to a non-technical audience. <br>

 - [ ] Unsupervised Learning [section 12.1](../files/ISLP.pdf#page=509) <br>
 - [ ] PCA [section 12.2](../files/ISLP.pdf#page=510) <br>
 - [ ] Clustering Models [section 12.4](../files/ISLP.pdf#page=526)<br>


## Related articles
 - [ ] [Decision making with AI](https://www.nature.com/articles/s41599-020-0501-9) (few years old) gives real-world examples of the ethical dilemmas of ML <br>

 - [ ] [Recommender system tutorial](https://www.alldatascience.com/recommender-systems/simple-recipe-recommender-system-with-scikit-surprise/)(won't cover in class but interesting unsupervised learning model) which you can get a better idea of how it works by writing out the 5-step ML workflow and fill in the steps you see being taken in the tutorial. <br>