# EVL readings


## ISLP selected readings
Dive deeper in the content we'll be covering. These articles can be quite math-heavy. If anything is unclear, don’t hesitate to reach out to your instructor. Aim to grasp the big-picture ideas so you can explain each topic to a non-technical audience. <br>

 - [ ] Intro to ML [section 2.1](../files/ISLP.pdf#page=25) <br>
 - [ ] Model Accuracy [section 2.2](../files/ISLP.pdf#page=37) <br>
 - [ ] Cross-validation [section 5.1](../files/ISLP.pdf#page=209) <br>
 - [ ] Bootstrap [section 5.2](../files/ISLP.pdf#page=220)<br>


## Related articles
 - [ ] [Accountable algorithms](https://www.fatml.org/resources/principles-for-accountable-algorithms) describes principles for investigating algorithms and holding them accountable. <br>

 - [ ] [Algorithm guidance](https://cdt.org/ai-machine-learning/) expands off of the accountable algorithms article to show some real-world examples. This is a bit long, so skim as needed. Pay attention to the real-world examples. <br>